services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres_db
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
